ecloning/ecloning/Models/ladder.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ladder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ladder()
        {
            this.ladder_size = new HashSet<ladder_size>();
        }
    
        public int id { get; set; }
        public string ladder_type { get; set; }
        public string name { get; set; }
        public int min_bp_kDa { get; set; }
        public int max_bp_kda { get; set; }
        public int company_id { get; set; }
        public string orderref { get; set; }
        public Nullable<double> a_values { get; set; }
        public Nullable<double> b_value { get; set; }
    
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ladder_size> ladder_size { get; set; }
    }
}

ecloning/ecloning/Areas/Admin/Controllers/LadderController.cs
using ecloning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Net;

namespace ecloning.Areas.Admin.Controllers
{
    public class LadderController : SubRootController
    {
        private ecloningEntities db = new ecloningEntities();

        // GET: Admin/Ladder
        [Authorize]
        [HttpGet]
        public ActionResult Index()
        {
            var ladder = db.ladders;
            return View(ladder.ToList());                   
        }
        public ActionResult Details(string type)
        {
            var ladder = db.ladders.Where(l=>l.ladder_type==type);
            ViewBag.Type = type;
            //get json data
            var ladderId = ladder.Select(i => i.id);
            var ladderSize = db.ladder_size.Where(l => ladderId.Contains(l.ladder_id)).OrderBy(l=>l.ladder_id).OrderBy(r=>r.Rf).Select(l => new {
                id = l.ladder_id,
                size = l.size,
                mass = l.mass,
                Rf = l.Rf
            });
            ViewBag.ladderSize = JsonConvert.SerializeObject(ladderSize.ToList());
            ViewBag.Type = type;
            return View(ladder.ToList());
        }
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.ladder_type = new SelectList(db.dropdownitems.Where(c=>c.category=="ladder").OrderBy(n => n.id), "value", "text");
            ViewBag.company_id = new SelectList(db.companies.OrderBy(n => n.shortName), "id", "shortName");
            ViewBag.Count = 1;
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create([Bind(Include = "id,ladder_type,name,company_id,orderref,ladderSize")] mladder mladder)
        {
            ViewBag.ladder_type = new SelectList(db.dropdownitems.Where(c => c.category == "ladder").OrderBy(n => n.id), "value", "text");
            ViewBag.company_id = new SelectList(db.companies.OrderBy(n => n.shortName), "id", "shortName");
            ViewBag.Count = mladder.ladderSize.Count();
            if (ModelState.IsValid)
            {
                //start transction
                using (TransactionScope scope = new TransactionScope())
                {
                    try
                    {                       
                        var ladder = new ladder();
                        ladder.ladder_type = mladder.ladder_type;
                        ladder.name = mladder.name;
                        ladder.company_id = mladder.company_id;
                        ladder.orderref = mladder.orderref;
                        //get the min and max fragment
                        ladder.min_bp_kDa = mladder.ladderSize.Select(s => s.size).Min();
                        ladder.max_bp_kda = mladder.ladderSize.Select(s => s.size).Max();
                        db.ladders.Add(ladder);
                        db.SaveChanges();

                        //find the newly added ladder
                        var nladder = db.ladders.Where(l => l.name == mladder.name && l.company_id == mladder.company_id).FirstOrDefault();

                        //add ladder_size
                        foreach(var item in mladder.ladderSize)
                        {
                            var ladderSize = new ladder_size();
                            ladderSize.ladder_id = nladder.id;
                            ladderSize.size = item.size;
                            ladderSize.mass = item.mass;
                            ladderSize.Rf = item.Rf;
                            db.ladder_size.Add(ladderSize);
                            db.SaveChanges();
                        }
                        scope.Complete();
                        TempData["msg"] = "Ladder added!";
                        return RedirectToAction("Details", new { type = mladder.ladder_type });
                    }
                    catch (Exception e)
                    {
                        var msg = e;
                        // If any exception is caught, roll back the entire transaction and end the scope.
                        scope.Dispose();
                        TempData["msg"] = "Something went wrong, ladder not added!";
                        return RedirectToAction("Details", new { type = mladder.ladder_type });

                    }
                }
            }
            return View(mladder);
        }


        [Authorize]
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ladder ladder = db.ladders.Find(id);
            if (ladder == null)
            {
                return HttpNotFound();
            }
            
            //load data into mladder
            var mladder = new mladder();
            mladder.id = ladder.id;
            mladder.company_id = ladder.company_id;
            mladder.ladder_type = ladder.ladder_type;
            mladder.name = ladder.name;
            mladder.orderref = ladder.orderref;

            //find ladder fragment
            var fragments = new List<ladderSize>();
            var ladderSize = db.ladder_size.Where(l => l.ladder_id == id).OrderBy(s=>s.size);
            foreach(var item in ladderSize.ToList())
            {
                var fragment = new ladderSize();
                fragment.size = item.size;
                fragment.mass = item.mass;
                fragment.Rf = item.Rf;
                fragments.Add(fragment);
            }
            mladder.ladderSize = fragments;
            ViewBag.ladder_type = new SelectList(db.dropdownitems.Where(c => c.category == "ladder").OrderBy(n => n.id), "value", "text", mladder.ladder_type);
            ViewBag.company_id = new SelectList(db.companies.OrderBy(n => n.shortName), "id", "shortName", mladder.company_id);
            ViewBag.Count = ladderSize.Count();
            return View(mladder);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit([Bind(Include = "id,ladder_type,name,company_id,orderref,ladderSize")] mladder mladder)
        {
            ViewBag.ladder_type = new SelectList(db.dropdownitems.Where(c => c.category == "ladder").OrderBy(n => n.id), "value", "text", mladder.ladder_type);
            ViewBag.company_id = new SelectList(db.companies.OrderBy(n => n.shortName), "id", "shortName", mladder.company_id);
            ViewBag.Count = mladder.ladderSize.Count();
            if (ModelState.IsValid)
            {
                using (TransactionScope scope = new TransactionScope())
                {
                    try
                    {
                        var ladder = db.ladders.Find(mladder.id);
                        ladder.ladder_type = mladder.ladder_type;
                        ladder.name = mladder.name;
                        ladder.company_id = mladder.company_id;
                        ladder.orderref = mladder.orderref;
                        //get the min and max fragment
                        ladder.min_bp_kDa = mladder.ladderSize.Select(s => s.size).Min();
                        ladder.max_bp_kda = mladder.ladderSize.Select(s => s.size).Max();

                        //remove all the existing fragments
                        var fragments = db.ladder_size.Where(l => l.ladder_id == mladder.id);
                        if (fragments.Count() > 0)
                        {
                            foreach (var item in fragments.ToList())
                            {
                                db.ladder_size.Remove(item);
                            }
                        }
                        //add new fragments
                        foreach (var item in mladder.ladderSize)
                        {
                            var ladderSize = new ladder_size();
                            ladderSize.ladder_id = mladder.id;
                            ladderSize.size = item.size;
                            ladderSize.mass = item.mass;
                            ladderSize.Rf = item.Rf;
                            db.ladder_size.Add(ladderSize);
                        }
                        db.SaveChanges();
                        scope.Complete();
                        TempData["msg"] = "ladder updated!";
                        return RedirectToAction("Details", new { type = mladder.ladder_type });
                    }
                    catch(Exception e)
                    {
                        var msg = e;
                        // If any exception is caught, roll back the entire transaction and end the scope.
                        scope.Dispose();
                        TempData["msg"] = "Something went wrong, ladder not added!";
                        return View(mladder);
                    }
                }               
            }
            return View(mladder);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ladder ladder = db.ladders.Find(id);
            if (ladder == null)
            {
                return HttpNotFound();
            }
            var ladderSize = db.ladder_size.Where(l =>l.ladder_id== ladder.id).OrderBy(l => l.ladder_id).OrderBy(r => r.Rf).Select(l => new {
                id = l.ladder_id,
                size = l.size,
                mass = l.mass,
                Rf = l.Rf
            });

ecloning/ecloning/Controllers/LadderController.cs
using ecloning.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ecloning.Controllers
{
    public class LadderController : RootController
    {
        private ecloningEntities db = new ecloningEntities();
        // GET: Ladder
        public ActionResult Index(string type)
        {
            var ladder = db.ladders.Where(l => l.ladder_type == type);
            //get json data
            var ladderId = ladder.Select(i => i.id);
            var ladderSize = db.ladder_size.Where(l => ladderId.Contains(l.ladder_id)).OrderBy(l => l.ladder_id).OrderBy(r => r.Rf).Select(l => new {
                id = l.ladder_id,
                size = l.size,
                mass = l.mass,
                Rf = l.Rf
            });
            ViewBag.ladderSize = JsonConvert.SerializeObject(ladderSize.ToList());
            ViewBag.Type = type;
            return View(ladder.ToList());
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ecloning/ecloning/Areas/Admin/Views/Ladder/Create.cshtml
@model ecloning.Models.mladder
@{
    ViewBag.Title = "Add Ladder";
    Layout = "~/Areas/Admin/Views/Shared/_BioToolsLayout.cshtml";
    var Count = (int)ViewBag.Count;
}

@Html.Partial("_BioTools")
<div id="page-wrapper">
    <div class="row">
        <div class="col-sm-10">
            <h3 class="text-primary"><span class="fa fa-plus"></span> Ladder</h3>
        </div>
        <div class="col-sm-2">
            <br class="hidden-xs" />
            <a class="btn btn-default pull-right" href="@Url.Action("Index", "Ladder")">
                <i class="fa fa-chevron-circle-left text-info"></i>
                <span class="">Cancel</span>
            </a>
        </div>
    </div>
    <div class="row">
        <hr />
        <div class="col-xs-12 col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Add Ladder
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-horizontal">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12" style="display: inline-block">                                    
                                        <div class="form-group required">
                                            @Html.LabelFor(model => model.ladder_type, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.DropDownList("ladder_type", null, "--  Select  --", htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.ladder_type, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group required">
                                            @Html.LabelFor(model => model.name, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group required">
                                            @Html.LabelFor(model => model.company_id, "Company", htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.DropDownList("company_id", null, "--  Select  --", htmlAttributes: new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.company_id, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.orderref, "Cat#", htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.orderref, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.orderref, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12" style="display: inline-block">
                                        <div class="form-group">
                                            <div class="col-xs-10">
                                                <p class="text-primary text-center">Fragment</p>
                                            </div>
                                            <div class="col-xs-2">
                                                <div class="pull-right">
                                                    <a class="btn btn-sm btn-default" data-toggle="tooltip" title="Add fragment" id="add_fragment">
                                                        <i class="fa fa-plus-circle text-primary"></i>
                                                    </a>
                                                    <a class="btn btn-sm btn-default" data-toggle="tooltip" title="Remove fragment" id="remove_fragment">
                                                        <i class="fa fa-minus-circle text-danger"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        @for (var i = 0; i < Count; i++)
                                        {
                                            var divId = "fragment-" + i;
                                            <div id=@divId class="fragmentDiv">
                                                <div class="col-xs-4">
                                                    <div class="form-group required">
                                                        @Html.LabelFor(model => model.ladderSize[i].size, "Size(bp)", htmlAttributes: new { @class = "control-label col-md-6" })
                                                        <div class="col-md-6">
                                                            @Html.EditorFor(model => model.ladderSize[i].size, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.ladderSize[i].size, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-4">
                                                    <div class="form-group required">
                                                        @Html.LabelFor(model => model.ladderSize[i].mass, "Mass", htmlAttributes: new { @class = "control-label col-md-6" })
                                                        <div class="col-md-6">
                                                            @Html.EditorFor(model => model.ladderSize[i].mass, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.ladderSize[i].mass, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-xs-4">
                                                    <div class="form-group required">
                                                        @Html.LabelFor(model => model.ladderSize[i].Rf, "Rf(mm)", htmlAttributes: new { @class = "control-label col-md-6" })
                                                        <div class="col-md-6">
                                                            @Html.EditorFor(model => model.ladderSize[i].Rf, new { htmlAttributes = new { @class = "form-control" } })
                                                            @Html.ValidationMessageFor(model => model.ladderSize[i].Rf, "", new { @class = "text-danger" })
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        }

                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Add Ladder" class="btn btn-primary pull-right" />
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
<script>
    $(document).ready(function () {
        $('#add_fragment').on('click', function () {
            var count = $('.fragmentDiv').length;
            console.log(count);
            var html = ladderSize(count);
            $('#fragment-0').parent().append(html);
        })
        $('#remove_fragment').on('click', function () {
            var count = $('.fragmentDiv').length;
            if (count > 1) {
                $('#fragment-' + (count - 1)).remove();
            }
            else {
                alert("Cannot remove the last fragment!");
            }           
        })
    });
    //add div for fragment size
    function ladderSize(count) {
        var html = "";
        html = html + '<div id="fragment-' + count + '" class="fragmentDiv">';

            html = html + '<div class="col-xs-4">';
                html = html + '<div class="form-group required">';
                    html = html + '<label class="control-label col-md-6" for="ladderSize_'+count+'__size">Size(bp)</label>';
                    html = html + '<div class="col-md-6">';
                        html = html + '<input class="form-control text-box single-line" data-val="true" data-val-number="The field size must be a number." data-val-required="Required" id="ladderSize_' + count + '__size" name="ladderSize[' + count + '].size" type="number" value="">';
                        html = html + '<span class="field-validation-valid text-danger" data-valmsg-for="ladderSize[' + count + '].size" data-valmsg-replace="true"></span>';
                    html = html + '</div>';
                html = html + '</div>';
            html = html + '</div>';


            html = html + '<div class="col-xs-4">';
                html = html + '<div class="form-group required">';
                    html = html + '<label class="control-label col-md-6" for="ladderSize_' + count + '__mass">Mass</label>';
                    html = html + '<div class="col-md-6">';
                        html = html + '<input class="form-control text-box single-line" data-val="true" data-val-number="The field mass must be a number." data-val-required="Required" id="ladderSize_' + count + '__mass" name="ladderSize[' + count + '].mass" type="number" value="">';
                        html = html + '<span class="field-validation-valid text-danger" data-valmsg-for="ladderSize[' + count + '].mass" data-valmsg-replace="true"></span>';
                    html = html + '</div>';
                html = html + '</div>';
            html = html + '</div>';


            html = html + '<div class="col-xs-4">';
                html = html + '<div class="form-group required">';
                    html = html + '<label class="control-label col-md-6" for="ladderSize_' + count + '__Rf">Rf(mm)</label>';
                    html = html + '<div class="col-md-6">';
                        html = html + '<input class="form-control text-box single-line" data-val="true" data-val-number="The field Rf must be a number." data-val-required="Required" id="ladderSize_' + count + '__Rf" name="ladderSize[' + count + '].Rf" type="text" value="">';
                        html = html + '<span class="field-validation-valid text-danger" data-valmsg-for="ladderSize[' + count + '].Rf" data-valmsg-replace="true"></span>';
                    html = html + '</div>';
                html = html + '</div>';
            html = html + '</div>';


        html = html + '</div>';
        return html;
    }
</script>

ecloning/ecloning/Areas/Admin/Views/Ladder/Details.cshtml
@model IEnumerable<ecloning.Models.ladder>
@{
    ViewBag.Title = "Ladders";
    Layout = "~/Areas/Admin/Views/Shared/_BioToolsLayout.cshtml";
    var ladderSize = ViewBag.ladderSize;
    var msg = TempData["msg"];
    var Type = ViewBag.Type;
}

@Html.Partial("_BioTools")
<div id="page-wrapper">
    <span id="decodeIt" class="hidden"></span>
    <span id="ladder_type" class="hidden">@Type</span>
    <div class="row">
        <div class="col-sm-10">
            <h3 class="text-primary"><i class="fa fa-barcode fa-rotate-270 fa-fw"></i> @ViewBag.Type Ladders</h3>
        </div>
        <div class="col-sm-2">
            <br class="hidden-xs" />
            <a class="btn btn-default pull-right" href="@Url.Action("Create", "Ladder")">
                <i class="fa fa-plus-circle text-info"></i>
                <span class="">Ladder</span>
            </a>
        </div>
        <p class="text-danger">@msg</p>
    </div>
    <div class="row">
        <hr/>
        @if (Model.Count() == 0)
        {
            <div class="text-danger">No ladder found! Please first add a ladder to continue.</div>
        }
        else
        {
            foreach(var item in Model)
            {
                //prepare svg id
                var id = "ladder-" + item.id;
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center"><em><strong>@item.name</strong></em></h3>
                        </div>
                        <div class="panel-body">
                            <div id="@id" class="inner"></div>
                        </div>
                        <div class="panel-footer clearfix">
                            <div>
                                <a class="btn btn-default" href="@Url.Action("Edit", "Ladder", new { id=item.id})" data-toggle="tooltip" title="Edit Ladder">
                                    <i class="fa fa-pencil-square-o"></i>
                                </a>
                                <a class="btn btn-default" href="@Url.Action("Delete", "Ladder", new { id=item.id})" data-toggle="tooltip" title="Delete Ladder">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/d3")
<script src="~/Scripts/ecloning.js"></script>
<script>
    //get json data
    var type = $("#ladder_type").text().trim();
    var ladders = ("@ladderSize");
    document.getElementById("decodeIt").innerHTML = ladders;
    ladders = document.getElementById("decodeIt").textContent;

    try
    {
        ladders = JSON.parse(ladders);
        //d3 nest by id
        var data = d3.nest()
                     .key(function (d) { return d.id; })
                     .entries(ladders);
        console.log(data);
        $.each(data, function (i, d) {
            var Rf = [];
            var size = [];
            var mass = [];
            $.each(d.values, function (si, sd) {
                Rf.push(sd.Rf); //Rf
                size.push(sd.size);
                mass.push(sd.mass);
            })
            //draw svg ladder
            //find the div id
            var id = "ladder-" + d.key;
            drawLadder(id, Rf, size, mass, d.values, type);
        })

    }
    catch (e)
    {
        console.log(e);
    }
    
</script>