ecloning/ecloning/Areas/Admin/Models/Restriction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ecloning.Areas.Admin.Models
{
    using ecloning.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Restriction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restriction()
        {
            this.activity_restriction = new HashSet<activity_restriction>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Required")]
        public string name { get; set; }
        [Required(ErrorMessage = "Required")]
        [RegularExpression("^[ATGCatgcRKBYSDWHNMVrkbysdwhnmv]*$", ErrorMessage = "Sequence can only contains letters: A, T, G, C, R, K, B, Y, S, D, W, H, N, M, V!")]
        public string forward_seq { get; set; }
        [Required(ErrorMessage = "Required")]
        [Range(-50, 50, ErrorMessage = "Please enter valid integer Number")]
        public int forward_cut { get; set; }
        [Required(ErrorMessage = "Required")]
        [Range(-50, 50, ErrorMessage = "Please enter valid integer Number")]
        public int reverse_cut { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<bool> staractitivity { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> inactivation { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<bool> dam { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<bool> dcm { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<bool> cpg { get; set; }
        [Range(-50, 50, ErrorMessage = "Please enter valid integer Number")]
        public int? forward_cut2 { get; set; }
        [Range(-50, 50, ErrorMessage = "Please enter valid integer Number")]
        public int? reverse_cut2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity_restriction> activity_restriction { get; set; }
    }
}

ecloning/ecloning/Models/restriction.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restriction
    {
        public int id { get; set; }
        public string name { get; set; }
        public string forward_seq { get; set; }
        public int forward_cut { get; set; }
        public string reverse_seq { get; set; }
        public int reverse_cut { get; set; }
        public Nullable<bool> methylation { get; set; }
        public Nullable<bool> common { get; set; }
    }
}

ecloning/ecloning/Areas/Admin/Controllers/RestrictionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ecloning.Models;
using ecloning.Areas.Admin.Models;
using System.Text;
using Newtonsoft.Json;
using System.Transactions;

namespace ecloning.Areas.Admin.Controllers
{
    public class RestrictionController : SubRootController
    {
        private ecloningEntities db = new ecloningEntities();

        // GET: Admin/Restriction
        [Authorize]
        public ActionResult Index()
        {
            var restris = db.restri_enzyme.OrderBy(n => n.name).ToList();
            return View(restris);
        }

        // GET: Admin/Restriction/Create
        [Authorize]
        public ActionResult Create()
        {
            //prepare dropdown list
            ViewBag.staractitivity = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", false);
            ViewBag.dam = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", false);
            ViewBag.dcm = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", false);
            ViewBag.cpg = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", true);
            ViewBag.inactivation = new SelectList(db.dropdownitems.Where(c => c.category == "StarActivity").OrderBy(g => g.id), "value", "text", 2);

            //prepare lette code
            var codes = db.letter_code.OrderBy(c => c.name);
            ViewBag.Codes = codes;
            return View();
        }

        // POST: Admin/Restriction/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,forward_seq,forward_cut,reverse_cut,staractitivity,inactivation,dam,dcm,cpg")] Restriction restriction)
        {
            //prepare dropdown list
            ViewBag.staractitivity = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", restriction.staractitivity);
            ViewBag.dam = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", restriction.dam);
            ViewBag.dcm = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", restriction.dcm);
            ViewBag.cpg = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", restriction.cpg);
            ViewBag.inactivation = new SelectList(db.dropdownitems.Where(c => c.category == "StarActivity").OrderBy(g => g.id), "value", "text", restriction.inactivation);
            //prepare lette code
            var codes = db.letter_code.OrderBy(c => c.name);
            ViewBag.Codes = codes;

            //check the name
            var enzymes = db.restri_enzyme.Where(n => n.name == restriction.name);
            if (enzymes.Count() > 0)
            {
                TempData["error"] = "Enzyme \""+restriction.name+"\" already exists!";
                return View(restriction);
            }

            //non zero validation
            if(restriction.forward_cut == 0 || restriction.reverse_cut == 0)
            {
                TempData["error"] = "Cut postion cann't be zero!";
                return View(restriction);
            }

            if (ModelState.IsValid)
            {
                //add to restri_enzyme
                var restri_enzyme = new restri_enzyme();
                restri_enzyme.name = restriction.name;
                restri_enzyme.forward_seq = restriction.forward_seq;
                restri_enzyme.forward_cut = restriction.forward_cut;
                restri_enzyme.reverse_cut = restriction.reverse_cut;
                restri_enzyme.staractitivity = restriction.staractitivity;
                restri_enzyme.dam = restriction.dam;
                restri_enzyme.dcm = restriction.dcm;
                restri_enzyme.cpg = restriction.cpg;
                restri_enzyme.inactivation = restriction.inactivation;
                db.restri_enzyme.Add(restri_enzyme);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restriction);
        }


        [Authorize]
        public ActionResult mCreate()
        {
            //prepare dropdown list
            ViewBag.staractitivity = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", false);
            ViewBag.dam = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", false);
            ViewBag.dcm = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", false);
            ViewBag.cpg = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", true);
            ViewBag.inactivation = new SelectList(db.dropdownitems.Where(c => c.category == "StarActivity").OrderBy(g => g.id), "value", "text", 2);

            //prepare lette code
            var codes = db.letter_code.OrderBy(c => c.name);
            ViewBag.Codes = codes;
            return View();
        }

        // POST: Admin/Restriction/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult mCreate([Bind(Include = "id,name,forward_seq,forward_cut,reverse_cut,forward_cut2,reverse_cut2,staractitivity,inactivation,dam,dcm,cpg")] Restriction restriction)
        {
            //prepare dropdown list
            ViewBag.staractitivity = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", restriction.staractitivity);
            ViewBag.dam = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", restriction.dam);
            ViewBag.dcm = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", restriction.dcm);
            ViewBag.cpg = new SelectList(db.dropdownitems.Where(c => c.category == "TF").OrderBy(g => g.id), "value", "text", restriction.cpg);
            ViewBag.inactivation = new SelectList(db.dropdownitems.Where(c => c.category == "StarActivity").OrderBy(g => g.id), "value", "text", restriction.inactivation);
            //prepare lette code
            var codes = db.letter_code.OrderBy(c => c.name);
            ViewBag.Codes = codes;

            //check the name
            var enzymes = db.restri_enzyme.Where(n => n.name == restriction.name);
            if (enzymes.Count() > 0)
            {
                TempData["error"] = "Enzyme \"" + restriction.name + "\" already exists!";
                return View(restriction);
            }
            //the most left cut must be smaller than the most right
            if (restriction.forward_cut > restriction.forward_cut2 || restriction.forward_cut > restriction.reverse_cut2)
            {
                TempData["error"] = "The forward cut position of the most left cut must be smaller than the cut positions of the most right cut!";
                return View(restriction);
            }
            if (restriction.reverse_cut > restriction.forward_cut2 || restriction.forward_cut > restriction.reverse_cut2)
            {
                TempData["error"] = "The complementary cut position of the most left cut must be smaller than the cut positions of the most right cut!";
                return View(restriction);
            }
            if (restriction.forward_cut2 == null || restriction.reverse_cut2 == null)
            {
                TempData["error"] = "Cut postions for the most right cut are required!";
                return View(restriction);
            }
            //non zero validation
            if (restriction.forward_cut == 0 || restriction.reverse_cut == 0 || restriction.forward_cut2 == 0 || restriction.reverse_cut2 == 0)
            {
                TempData["error"] = "Cut postion cann't be zero!";
                return View(restriction);
            }

            if (ModelState.IsValid)
            {
                //add to restri_enzyme
                var restri_enzyme = new restri_enzyme();
                restri_enzyme.name = restriction.name;
                restri_enzyme.forward_seq = restriction.forward_seq;
                restri_enzyme.forward_cut = restriction.forward_cut;
                restri_enzyme.reverse_cut = restriction.reverse_cut;
                restri_enzyme.forward_cut2 = restriction.forward_cut2;
                restri_enzyme.reverse_cut2 = restriction.reverse_cut2;
                restri_enzyme.staractitivity = restriction.staractitivity;
                restri_enzyme.dam = restriction.dam;
                restri_enzyme.dcm = restriction.dcm;
                restri_enzyme.cpg = restriction.cpg;
                restri_enzyme.inactivation = restriction.inactivation;
                db.restri_enzyme.Add(restri_enzyme);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restriction);
        }

        [Authorize]
        public ActionResult preDelete()
        {
            //get all enzymes

ecloning/ecloning/Areas/Admin/Views/Restriction/Create.cshtml
@model ecloning.Areas.Admin.Models.Restriction

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_BioToolsLayout.cshtml";
    var Codes = (IOrderedQueryable<ecloning.Models.letter_code>)ViewBag.Codes;
}


@Html.Partial("_BioTools")

<div id="page-wrapper">
    <div class="row">
        <div class="col-sm-10">
            <h3 class="text-primary"><span class="fa fa-plus"></span> Restriction Enzyme</h3>
        </div>
        <div class="col-sm-2">
            <br class="hidden-xs" />
            <a class="btn btn-default" href="@Url.Action("mCreate", "Restriction")">
                <i class="fa fa-toggle-off  text-danger"></i>
                <span class="">Multiple Cuts</span>
            </a>
            <a class="btn btn-default pull-right" href="@Url.Action("Index", "Restriction")">
                <i class="fa fa-chevron-circle-left text-info"></i>
                <span class="">Cancel</span>
            </a>
        </div>
    </div>
    <div class="row">
        <hr/>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Restriction Enzyme with Only One Cut
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1">
                            <p class="text-danger">@TempData["error"]</p>
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-horizontal">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.name, "Enzyme Name", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.forward_seq, "Forward Sequence (5' - 3')", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.forward_seq, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.forward_seq, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.forward_cut, "Forward Cut Position", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.forward_cut, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.forward_cut, "", new { @class = "text-danger" })
                                            <p><span class="text-info" style="font-size:80%;"><em>Position starts with 1 and fill the position before the cut</em></span></p>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.reverse_cut, "Complementary Cut Position", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.EditorFor(model => model.reverse_cut, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.reverse_cut, "", new { @class = "text-danger" })
                                            <p><span class="text-info" style="font-size:80%;"><em>Position starts with 1 and fill the position before the cut</em></span></p>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.staractitivity, "Star Activity", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.DropDownList("staractitivity", null, "--  Select  --", htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.staractitivity, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.inactivation, "Heat Inactivation", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.DropDownList("inactivation", null, "--  Select  --", htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.inactivation, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.dam, "Dam Sensitivity", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.DropDownList("dam", null, "--  Select  --", htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.dam, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.dcm, "Dcm Sensitivity", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.DropDownList("dcm", null, "--  Select  --", htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.dcm, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.cpg, "CpG Sensitivity", htmlAttributes: new { @class = "control-label col-md-4" })
                                        <div class="col-md-8">
                                            @Html.DropDownList("cpg", null, "--  Select  --", htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.cpg, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group pull-right">
                                        <div class="col-md-offset-2 col-md-2">
                                            <input type="submit" value="Add Enzyme" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    How to find cut positions
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
                            <div id="cut_prototype">
                                    <img src="~/images/xbaI.jpg" class="img-rounded img-responsive" alt="xbaI"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br/>
            <div class="panel panel-info">
                <div class="panel-heading">
                    Letter Codes
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
                            <div id="letter_code" class="row">
                                <div class="table-responsive">
                                    <table class="table table-condensed">
                                        <thead>
                                            <tr>
                                                <th>Letter Codes</th>
                                                <th>Necleotides</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach(var item in Codes.ToList())
                                            {
                                                <tr>
                                                    <td>
                                                        @item.name
                                                    </td>
                                                    <td>
                                                        @item.necleotide
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ecloning/ecloning/Areas/Admin/Views/Restriction/preDelete.cshtml

@{
    ViewBag.Title = "preDelete";
    Layout = "~/Areas/Admin/Views/Shared/_BioToolsLayout.cshtml";
    var msg = (string)ViewBag.msg;
    var Enzymes = ViewBag.Enzymes;
}

@Html.Partial("_BioTools")
<div id="page-wrapper">
    <div class="row">
        <div class="col-sm-9">
            <h3 class="text-danger"><span class="fa fa-trash-o"></span> Delete Enzymes</h3>
        </div>
        <div class="col-sm-3">
            <br class="hidden-xs" />
            <a class="btn btn-default pull-right" href="@Url.Action("Index", "Restriction")">
                <i class="fa fa-chevron-circle-left text-info"></i>
                <span class="">Cancel</span>
            </a>
        </div>
        <span id="decodeIt" class="hidden"></span>
    </div>
    <div class="row">
        <hr/>
        <div class="col-md-12 col-lg-10 col-lg-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    <p class="text-danger">@msg</p>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <label for="feature" class="required">Search restriction enzymes to delete: </label>
                            <input type="text" name="enzyme" class="form-control" id="enzyme">
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-10 col-md-2 col-sm-offset-9 col-sm-3 col-xs-12 pull-right">
                                <input type="submit" value="Delete Enzymes" class="btn btn-block btn-danger" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
<script>
    var JsonData = ("@Enzymes");
    document.getElementById("decodeIt").innerHTML = JsonData;
    JsonData = document.getElementById("decodeIt").innerText;

    try {
        data = JSON.parse(JsonData);
    } catch (e) {
    }

    $(document).ready(function () {
        $("#enzyme").tokenInput(data, {
            theme: 'facebook',
            hintText: 'Type enzyme name to search',
            tokenLimit: 5,
            propertyToSearch: "name",
            resultsFormatter: function (item) { return "<li><p><b style='color: red'>" + item.name + " </b></p></li>" },
            tokenFormatter: function (item) { return "<li><p><b style='color: red'>" + item.name + "</b></p></li>" },
        });

        $("form div ul").addClass('token-input-list-facebook form-control text-box single-line');
    });
</script>