ecloning/ecloning/Areas/Admin/Controllers/RActivityController.cs
using ecloning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace ecloning.Areas.Admin.Controllers
{
    public class RActivityController : SubRootController
    {
        private ecloningEntities db = new ecloningEntities();
        // GET: Admin/RActivity
        [Authorize]
        public ActionResult Index()
        {

            return View();
        }

        [Authorize]
        public ActionResult EnzymeList(int company_id)
        {
            //get the comany
            var company = db.companies.Where(c => c.id == company_id);
            if (company.Count() == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //get company restriction enzyme list
            var enzymes = db.restriction_company.Where(c => c.company_id == company_id);
            List<int> enzymeId = new List<int>();
            if (enzymes.Count() > 0)
            {
                enzymeId = enzymes.Select(e => e.enzyme_id).ToList();
            }
            ViewBag.Count = enzymes.Count();  //show that there is no enzyme
            ViewBag.CompanyId = company_id;
            ViewBag.Company = company.FirstOrDefault().shortName;
            ViewBag.EnzymeId = enzymeId;

            //load data to model RestrictionActivity
            List<RestrictionActivity> RActivityList = new List<RestrictionActivity>();

            //first get active buffer
            var buffers = db.buffers.Where(b => b.company_id == company_id && b.show_activity != false).OrderBy(b => b.name).ToList();
            var bufferId = buffers.Select(i => i.id).ToList();
            var bufferName = buffers.Select(i => i.name).ToList();
            ViewBag.BufferCount = buffers.Count(); //don't show buffer and activity
            ViewBag.BufferId = bufferId;
            ViewBag.bufferName = bufferName;

            var restri = db.restri_enzyme.Where(r => enzymeId.Contains(r.id)).ToList();
            if (enzymes.Count() > 0)
            {
                //first load the activities;
                var activities = db.activity_restriction.Where(a => a.company_id == company_id);
                foreach (var e in restri)
                {
                    var RActivity = new RestrictionActivity();
                    RActivity.company_id = company_id;
                    RActivity.enzyme_id = e.id;
                    RActivity.enzymeName = e.name;
                    RActivity.forward_seq = e.forward_seq;
                    RActivity.forward_cut = e.forward_cut;
                    RActivity.forward_cut2 = e.forward_cut2;
                    RActivity.reverse_cut2 = e.reverse_cut2;
                    RActivity.reverse_cut = e.reverse_cut;
                    RActivity.starActivity = e.staractitivity;
                    RActivity.dam = e.dam;
                    RActivity.dcm = e.dcm;
                    RActivity.cpg = e.cpg;
                    RActivity.inactivity = e.inactivation;

                    List<Activity> bufferActivity = new List<Activity>();
                    //uncoment this if want to show buffer info

                    if (buffers.Count() > 0)
                    {
                        //find activity                           
                        var enzymeActivities = activities.Where(a => a.enzyme_id == e.id).Where(b => bufferId.Contains(b.buffer_id)).OrderBy(b => b.buffer_id).ToList();
                        if (enzymeActivities.Count() > 0)
                        {
                            foreach (var b in enzymeActivities)
                            {
                                Activity Activity = new Activity();
                                Activity.id = b.buffer_id; //buffer id 
                                Activity.bufferName = b.buffer.name;//buffer name
                                Activity.activity = b.activity; //enzyme activity
                                bufferActivity.Add(Activity);
                                RActivity.temprature = b.temprature;
                            }
                        }
                    }

                    RActivity.Activity = bufferActivity;
                    RActivityList.Add(RActivity);
                }
            }
            return View(RActivityList.ToList());
        }

        [Authorize]
        [HttpPost]
        public ActionResult EnzymeList(string type, int company_id, int pk, int value)
        {
            if (type == "activity")
            {
                //find the activity
                var activity = db.activity_restriction.Find(pk);
                if( activity != null)
                {
                    activity.activity = value;
                }
            }
            if (type == "temprature")
            {
                //find the all the activity of this enzyme
                var activities = db.activity_restriction.Where(a => a.enzyme_id == pk && a.company_id == company_id);
                if (activities.Count() > 0)
                {
                    foreach(var a in activities)
                    {
                        a.temprature = value;
                    }
                }
            }
            db.SaveChanges();
            return RedirectToAction("EnzymeList", new { company_id = company_id });
        }

        [Authorize]
        public ActionResult Delete(int? enzyme_id, int? company_id)
        {
            //get the comany
            if (enzyme_id == null || company_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var company = db.companies.Where(c => c.id == company_id);
            if (company.Count() == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //find the enzyme
            var enzyme = db.restriction_company.Where(e => e.company_id == (int)company_id && e.enzyme_id == (int)enzyme_id);
            using (TransactionScope scope = new TransactionScope())
            {
                try
                {
                    if (enzyme.Count() == 0)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    else
                    {
                        //remove that enzyme
                        db.restriction_company.Remove(enzyme.FirstOrDefault());

                        //remove all the activity
                        var activities = db.activity_restriction.Where(e => e.company_id == (int)company_id && e.enzyme_id == (int)enzyme_id);
                        if (activities.Count() > 0)
                        {
                            foreach (var a in activities.ToList())
                            {
                                db.activity_restriction.Remove(a);
                            }
                        }
                        db.SaveChanges();
                    }
                    scope.Complete();
                    return RedirectToAction("EnzymeList", new { company_id = company_id });
                }
                catch (Exception)
                {
                    scope.Dispose();
                    return RedirectToAction("EnzymeList", new { company_id = company_id });
                }
            }

        }

        [Authorize]
        public ActionResult AddEnzyme(int company_id)
        {
            //get the comany
            var company = db.companies.Where(c => c.id == company_id);
            if (company.Count() == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //get company restriction enzyme list
            var enzymes = db.restriction_company.Where(c => c.company_id == company_id);
            List<int> enzymeId = new List<int>();
            if (enzymes.Count() > 0)
            {
                enzymeId = enzymes.Select(e => e.enzyme_id).ToList();
            }
            ViewBag.CompanyId = company_id;
            ViewBag.Company = company.FirstOrDefault().shortName;
            //get the enzymes that are not in the company
            var enzymeList = db.restri_enzyme.Where(i => !enzymeId.Contains(i.id)).ToList();
            return View(enzymeList);
        }


        [Authorize]
        public ActionResult AddToCompany(int? enzyme_id, int? company_id)
        {
            //get the comany
            if(enzyme_id == null || company_id== null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var company = db.companies.Where(c => c.id == company_id);
            if (company.Count() == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //start transction
            using (TransactionScope scope = new TransactionScope())
            {
                try
                {
                    //add to company list
                    var enzyme = new restriction_company();
                    enzyme.company_id = (int)company_id;
                    enzyme.enzyme_id = (int)enzyme_id;
                    db.restriction_company.Add(enzyme);

                    //create empty activity in activity_restriction table
                    //get all buffer id
                    var buffers = db.buffers.Where(c => c.company_id == company_id);
                    if (buffers.Count() > 0)
                    {
                        foreach(var b  in buffers)
                        {

ecloning/ecloning/Areas/Admin/Views/RActivity/AddEnzyme.cshtml
@model IEnumerable<ecloning.Models.restri_enzyme>
@{
    ViewBag.Title = "EnzymeList";
    Layout = "~/Areas/Admin/Views/Shared/_BioToolsLayout.cshtml";
    int CompanyId = (int)ViewBag.CompanyId;
    string Company = (string)ViewBag.Company;
}

@Html.Partial("_BioTools")
<div id="page-wrapper">
    <div class="row">
        <div class="col-sm-9">
            <h3 class="text-primary"><span><i class="fa fa-plus-circle">&nbsp;</i></span>Add Enzymes to @Company</h3>
        </div>
        <div class="col-sm-3">
            <br class="hidden-xs" />
            <a class="btn btn-default pull-right" href="@Url.Action("EnzymeList", "RActivity", new { company_id = CompanyId})">
                <i class="fa fa-caret-left text-info"></i>
                <span class="">Done</span>
            </a>
        </div>
    </div>
    <div class="row">
        <hr />
        <div class="col-md-12 col-lg-10 col-lg-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-10">
                            <div class="btn-toolbar">
                                <div class="btn-group btn-group-sm" id="alphabet">
                                    <button class="btn btn-default">All</button>
                                    <button class="btn btn-default">A</button>
                                    <button class="btn btn-default">B</button>
                                    <button class="btn btn-default">C</button>
                                    <button class="btn btn-default">D</button>
                                    <button class="btn btn-default">E</button>
                                    <button class="btn btn-default">F</button>
                                    <button class="btn btn-default">G</button>
                                    <button class="btn btn-default">H</button>
                                    <button class="btn btn-default">I</button>
                                    <button class="btn btn-default">J</button>
                                    <button class="btn btn-default">K</button>
                                    <button class="btn btn-default">L</button>
                                    <button class="btn btn-default">M</button>
                                    <button class="btn btn-default">N</button>
                                    <button class="btn btn-default">O</button>
                                    <button class="btn btn-default">P</button>
                                    <button class="btn btn-default">Q</button>
                                    <button class="btn btn-default">R</button>
                                    <button class="btn btn-default">S</button>
                                    <button class="btn btn-default">T</button>
                                    <button class="btn btn-default">U</button>
                                    <button class="btn btn-default">V</button>
                                    <button class="btn btn-default">W</button>
                                    <button class="btn btn-default">X</button>
                                    <button class="btn btn-default">Y</button>
                                    <button class="btn btn-default">Z</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <hr />
                        <div class="table-responsive">
                            <table class="table table-condensed" id="enzyme-table">
                                <thead>
                                    <tr>
                                        <th class="text-center col-sm-2 no-sort">
                                            Enzyme
                                        </th>
                                        <th class="text-center">
                                            Prototype
                                        </th>
                                        <th class="text-center">
                                        </th>
                                    </tr>

                                </thead>
                                @foreach (var item in Model)
                                {
                                    var enzymeSybol = new ecloning.Models.RestrictionEnzyme();
                                    <tr id=@item.name.ToLower()>
                                        <td class="text-center">
                                            <strong class="text-warning">@Html.DisplayFor(modelItem => item.name)</strong>
                                        </td>
                                        <td class="text-center">
                                            @if (item.forward_cut2 != null && item.reverse_cut2 != null)
                                            {
                                                @Html.Raw(enzymeSybol.ShowPrototype2(item.forward_seq, item.forward_cut, item.reverse_cut, (int)item.forward_cut2, (int)item.reverse_cut2))
                                            }
                                            else
                                            {
                                                @Html.Raw(enzymeSybol.ShowPrototype(item.forward_seq, item.forward_cut, item.reverse_cut))
                                            }
                                        </td>
                                        <td class="vert-align">
                                            <a href="@Url.Action("AddToCompany", "RActivity", new { enzyme_id = item.id, company_id = CompanyId })">
                                                <i class="fa fa-plus-circle fa-3x text-info"></i>
                                                <span class=""></span>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@Scripts.Render("~/bundles/jquery")
<script>
    $(function () {
        var _alphabets = $('#alphabet > button');
        var _contentRows = $('#enzyme-table tbody tr');

        _alphabets.click(function () {
            var _letter = $(this),
                _text = $(this).text().toLowerCase(),
                _count = 0;

            _alphabets.removeClass("active");
            _letter.addClass("active");

            _contentRows.hide();
            _contentRows.each(function (i) {
                var _cellText = $(this).children('td').eq(0).text().toLowerCase().replace(/\s+/g, '');
                if (_text === 'all') {
                    _count += 1;
                    $(this).fadeIn(400);
                } else {
                    if (RegExp('^' + _text).test(_cellText)) {
                        _count += 1;
                        $(this).fadeIn(400);
                    }
                }
            });
        });
    });
</script>

ecloning/ecloning/Areas/Admin/Views/RActivity/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_BioToolsLayout.cshtml";
    var db = new ecloning.Models.ecloningEntities();
    //find the company
    var companies = db.companies;
    int Count = companies.Count();


    
}

@Html.Partial("_BioTools")
<div id="page-wrapper">
    <div class="row">
        <div class="row">
            <div class="col-sm-9">
                <h3 class="text-primary"><span><i class="fa fa-flask">&nbsp;</i></span>Restriction Enzymes by Companies</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <hr/>
        <div class="col-md-12 col-lg-10 col-lg-offset-1">
            @if(Count == 0)
            {
                <div class="text-danger">No company found! Please first add a company to continue.</div>
            }
            else
            {
                foreach (var c in companies)
                {

                    //find the enzymes for each company
                    int enzymeNum = 0;
                    var cEnzyme = db.restriction_company.Where(n => n.company_id == c.id);
                    if(cEnzyme.Count() > 0)
                    {
                        enzymeNum = cEnzyme.Select(e => e.enzyme_id).Distinct().Count();
                    }

                    //find the buffers, if no buffer found disable the button
                    int bufferCount = db.buffers.Where(i => i.company_id == c.id).Count();
                    if (bufferCount == 0)
                    {
                        <div class="list-group">
                            <a class="list-group-item disabled" href="@Url.Action("EnzymeList", "RActivity", new { company_id = c.id})">
                                <h4 class="list-group-item-heading">
                                    <i class="fa fa-building-o text-info"></i>
                                    <span class="text-primary"><strong>@c.shortName</strong></span>
                                    <span class="badge pull-right"><span>#Enzymes:</span> @enzymeNum</span>
                                </h4>
                                <p class="list-group-item-text"><span class="text-info">@c.fullName </span><span>@c.des</span></p>
                            </a>
                        </div>
                    }
                    else
                    {
                        <div class="list-group">
                            <a class="list-group-item" href="@Url.Action("EnzymeList", "RActivity", new { company_id = c.id})">
                                <h4 class="list-group-item-heading">
                                    <i class="fa fa-building-o text-info"></i>
                                    <span class="text-primary"><strong>@c.shortName</strong></span>
                                    <span class="badge pull-right"><span>#Enzymes:</span> @enzymeNum</span>
                                </h4>
                                <p class="list-group-item-text"><span class="text-info">@c.fullName </span><span>@c.des</span></p>
                            </a>
                        </div>
                    }


                }
            }
        </div>
    </div>
</div>
